package HWK7;

import javax.net.ssl.HttpsURLConnection;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.StringTokenizer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leader
 */
public class MI3C_HWK7_412630153_02 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MI3C_HWK7_412630153_02.class.getName());

    /**
     * Creates new form HWK7_412630153
     */
    public MI3C_HWK7_412630153_02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rltTa = new javax.swing.JTextArea();
        searchBtn = new javax.swing.JButton();
        queryTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rltTa.setColumns(20);
        rltTa.setRows(5);
        jScrollPane1.setViewportView(rltTa);

        searchBtn.setText("Google");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        queryTf.setText("F35");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(searchBtn)
                .addGap(18, 18, 18)
                .addComponent(queryTf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(queryTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        //doSearch(); //如果爬蟲失敗，請幫我解開下面三個甘溫。
        String htmlTXT = "C:/Data/TKU_HTML.txt";
        doSearch(htmlTXT);
        queryTf.setText(htmlTXT.substring(htmlTXT.lastIndexOf("/")+1, htmlTXT.lastIndexOf(".")));
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MI3C_HWK7_412630153_02().setVisible(true));
    }
    public void doSearch(String htmlTXT){
        new Thread(() -> {
            try {
                String html = getSource(htmlTXT);
                StringTokenizer st = new StringTokenizer(html, "<>=\" ", true);
                int state = 0;
                boolean rlt = false;
                String header = "", url = "";
                String destFileName = String.format("%s%s", htmlTXT.substring(0, htmlTXT.indexOf('.')) , "_url.txt");
                File f = new File(destFileName);
                try(PrintWriter pw = new PrintWriter(f)){
                    while (st.hasMoreTokens()) {
                        String token = st.nextToken();
                        if (token.equals(" ")) continue; 
                        switch (state) {
                            case 0: 
                                if (token.equalsIgnoreCase("a")) {
                                    url = ""; header = ""; rlt = false;
                                    state = 1;
                                }
                                break;

                            case 1: 
                                if (token.equals("jsname")) state = 2;
                                else if (token.equals("href")) state = 3;
                                else if (token.equals(">")) {

                                    if (rlt && !url.isEmpty()) state = 4;
                                    else state = 0;
                                }
                                break;

                            case 2: 
                                if (token.equalsIgnoreCase("UWckNb")) {
                                    rlt = true;
                                    state = 1;
                                }
                                break;

                            case 3:
                                if (token.equals("\"")) {
                                    StringBuilder sb = new StringBuilder();
                                    while (st.hasMoreTokens()) {
                                        String part = st.nextToken();
                                        if (part.equals("\"")) break; 
                                        sb.append(part);
                                    }
                                    url = sb.toString();
                                    state = 1;
                                }
                                break;

                            case 4: 
                                if (token.equalsIgnoreCase("h3")) state = 5;
                                else if (token.equals("/")) state = 0; 
                                break;

                            case 5: 
                                if (token.equals(">")) {
                                    StringBuilder sb = new StringBuilder();
                                    while (st.hasMoreTokens()) {
                                        String part = st.nextToken();
                                        if (part.equals("<")) break;
                                        sb.append(part);
                                    }
                                    header = sb.toString().trim();


                                    if (!header.isEmpty() && url.startsWith("http")) {
                                        rltTa.append("# " + header + "\n");
                                        rltTa.append(url + "\n");
                                        rltTa.append("--------------------------------------\n");
                                        pw.print(String.format("#%s\n%s\n--------------------------------------\n", header, url));
                                    }
                                    state = 0;
                                }
                                break;
                        }
                    }
                }
                
            } catch (Exception e) {
                rltTa.append(e.getMessage());
            }
        }).start();
    }
    public void doSearch(){
        new Thread(() -> {
            try {
                String html = getSource();
                StringTokenizer st = new StringTokenizer(html, "<>=\" ", true);
                int state = 0;
                boolean rlt = false;
                String query = queryTf.getText();
                String header = "", url = "";
                String destFileName = String.format("%s%s", query, "_url.txt");
                File f = new File(destFileName);
                try(PrintWriter pw = new PrintWriter(f)){
                    if (html == null || !html.contains("<h3>")) {
                        rltTa.setText("爬蟲失敗，請助教解開 searchBtnActionPerformed 中的註解甘溫\n");
                        pw.print("爬蟲失敗，請助教解開 searchBtnActionPerformed 中的註解甘溫");
                        System.out.println("爬蟲失敗，請助教解開 searchBtnActionPerformed 中的註解甘溫");
                        return;
                    }
                    while (st.hasMoreTokens()) {
                        String token = st.nextToken();
                        if (token.equals(" ")) continue; 
                        switch (state) {
                            case 0: 
                                if (token.equalsIgnoreCase("a")) {
                                    url = ""; header = ""; rlt = false;
                                    state = 1;
                                }
                                break;

                            case 1: 
                                if (token.equals("jsname")) state = 2;
                                else if (token.equals("href")) state = 3;
                                else if (token.equals(">")) {

                                    if (rlt && !url.isEmpty()) state = 4;
                                    else state = 0;
                                }
                                break;

                            case 2: 
                                if (token.equalsIgnoreCase("UWckNb")) {
                                    rlt = true;
                                    state = 1;
                                }
                                break;

                            case 3:
                                if (token.equals("\"")) {
                                    StringBuilder sb = new StringBuilder();
                                    while (st.hasMoreTokens()) {
                                        String part = st.nextToken();
                                        if (part.equals("\"")) break; 
                                        sb.append(part);
                                    }
                                    url = sb.toString();
                                    state = 1;
                                }
                                break;

                            case 4: 
                                if (token.equalsIgnoreCase("h3")) state = 5;
                                else if (token.equals("/")) state = 0; 
                                break;

                            case 5: 
                                if (token.equals(">")) {
                                    StringBuilder sb = new StringBuilder();
                                    while (st.hasMoreTokens()) {
                                        String part = st.nextToken();
                                        if (part.equals("<")) break;
                                        sb.append(part);
                                    }
                                    header = sb.toString().trim();
                                    if (!header.isEmpty() && url.startsWith("http")) {
                                        rltTa.append("# " + header + "\n");
                                        rltTa.append(url + "\n");
                                        rltTa.append("--------------------------------------\n");
                                        pw.print(String.format("#%s\n%s\n--------------------------------------\n", header, url));
                                    }
                                    state = 0;
                                }
                                break;
                        }
                    }
                }
            } catch (Exception e) {
                rltTa.append(e.getMessage());
            }
        }).start();
    }
    public String getSource(){
        String html = "";
        try{
            String part1 = "https://www.google.com.tw/search?hl=zh-TW&q=";
            String qString = URLEncoder.encode(queryTf.getText(),"utf-8");
            String part2 = "&meta=&aq=f&gws_rd=ssl";
            URL url = new URL(part1+qString+part2) ;
            System.out.println(url.toExternalForm());
            HttpsURLConnection uc = (HttpsURLConnection) url.openConnection();
            uc.addRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36)");
            try(BufferedReader br = new BufferedReader(new InputStreamReader(uc.getInputStream(), "UTF-8"))){
                StringBuilder temp = new StringBuilder();
                String line;
                while ((line = br.readLine()) != null) {
                    temp.append(line);
                }
                html = temp.toString();
            }catch(Exception e){
                e.printStackTrace();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return html;
    }
    public static String getSource(String path){
        File f = new File(path);
        StringBuilder sb = new StringBuilder();
        try(BufferedReader br = new BufferedReader(new FileReader(f))){
            String aLine = "";
            while((aLine = br.readLine()) != null){
                sb.append(aLine).append("\n");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return sb.toString();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField queryTf;
    private javax.swing.JTextArea rltTa;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
